"""Plain Language Summary agent — 4-paragraph non-specialist summary via Grok."""
from __future__ import annotations

from typing import Any

import structlog

logger = structlog.get_logger(__name__)

_SMART_MODEL = "llama-3.3-70b-versatile"

SYSTEM = """You are a science communicator writing for educated non-specialists.
Write a 4-paragraph plain-language summary (300–500 words total) of a research paper.

Paragraph 1 — What the paper claims: the main finding in plain English.
Paragraph 2 — How it was studied: the methods in accessible language.
Paragraph 3 — What to know about reliability: acknowledge any flagged statistical or citation concerns (if provided); if concerns are medium or high severity mention 'A reviewer should double-check…'.
Paragraph 4 — What to read next: suggest related reading or context.

IMPORTANT: Begin the summary with this exact line:
"This summary is generated by AI for reader convenience and is not a substitute for the paper itself."

Keep jargon minimal. If you use a technical term, explain it immediately. Length: 300–500 words."""


async def run(parsed_paper: dict[str, Any], findings_so_far: list[dict], paper_id: str) -> list[dict[str, Any]]:
    abstract = parsed_paper.get("abstract") or ""
    sections = parsed_paper.get("sections", [])
    language = parsed_paper.get("language", "en")

    # Build input text
    body = abstract
    if not body:
        body = " ".join(s["text"] for s in sections)[:1500]

    concern_lines: list[str] = []
    for f in findings_so_far:
        if f.get("severity") in ("medium", "high"):
            concern_lines.append(f"- {f['title']}")

    concerns_text = ""
    if concern_lines:
        concerns_text = "\n\nFlagged concerns from other agents:\n" + "\n".join(concern_lines)

    lang_note = ""
    if language and language != "en":
        lang_note = f"\n\nNote: the original paper appears to be in {language}. Write the summary in English."

    prompt = (
        f"Paper abstract / text:\n{body[:3000]}"
        f"{concerns_text}"
        f"{lang_note}"
    )

    try:
        from peerless.agents.llm import LLMUnavailable, generate_text
        summary_text = await generate_text(
            model=_SMART_MODEL,
            system=SYSTEM,
            prompt=prompt,
            max_tokens=1024,
            agent_name="plain_language_summary",
            use_cache=True,
        )

    except Exception as exc:
        logger.warning("plain_language_summary.error", error=str(exc))
        return [{
            "agent": "plain_language_summary",
            "severity": "info",
            "confidence": 0.0,
            "title": "Plain-language summary unavailable",
            "summary": "Could not generate summary (LLM unavailable or key not set).",
            "evidence": [],
            "requires_human_review": True,
            "status": "draft",
        }]

    return [{
        "agent": "plain_language_summary",
        "severity": "info",
        "confidence": 0.9,
        "title": "Plain-language summary",
        "summary": summary_text,
        "evidence": [{"kind": "text", "content": {"source": _SMART_MODEL, "word_count": len(summary_text.split())}}],
        "requires_human_review": False,
        "status": "draft",
        "_is_summary": True,
        "_summary_text": summary_text,
    }]
