/**
 * Canonical disclaimer text — single source of truth used in layout, report header, and PDF export.
 */
export const DISCLAIMER_FULL =
  "PEERLESS.AI surfaces possible concerns in a paper for expert review. " +
  "It does not adjudicate misconduct. Findings are not conclusions. " +
  "All findings are flagged concerns pending human review.";

export const DISCLAIMER_SHORT =
  "Findings are flagged concerns for expert review — not conclusions.";

export const AI_SUMMARY_NOTICE =
  "This summary is generated by AI for reader convenience and is not a substitute for the paper itself.";
